// <auto-generated />
using System;
using ChatGPTInterface;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatGPTInterface.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331230202_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatGPTInterface.KnowledgeVectorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KnowledgeRecordId")
                        .HasColumnType("int");

                    b.Property<double>("VectorValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeRecordId");

                    b.ToTable("KnowledgeVectorItems");
                });

            modelBuilder.Entity("SemanticSearch.KnowledgeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeRecords");
                });

            modelBuilder.Entity("ChatGPTInterface.KnowledgeVectorItem", b =>
                {
                    b.HasOne("SemanticSearch.KnowledgeRecord", null)
                        .WithMany("KnowledgeVector")
                        .HasForeignKey("KnowledgeRecordId");
                });

            modelBuilder.Entity("SemanticSearch.KnowledgeRecord", b =>
                {
                    b.Navigation("KnowledgeVector");
                });
#pragma warning restore 612, 618
        }
    }
}
